<?php

namespace ContainerU7taWFo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DeERYOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.De_eRYO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.De_eRYO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'attachement' => ['privates', '.errored..service_locator.De_eRYO.App\\Entity\\Attachement', NULL, 'Cannot autowire service ".service_locator.De_eRYO": it references class "App\\Entity\\Attachement" but no such service exists.'],
            'attachementRepository' => ['privates', 'App\\Repository\\AttachementRepository', 'getAttachementRepositoryService', true],
        ], [
            'attachement' => 'App\\Entity\\Attachement',
            'attachementRepository' => 'App\\Repository\\AttachementRepository',
        ]);
    }
}
