<?php

namespace ContainerU7taWFo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GIPdewUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gIPdewU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gIPdewU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AttachementController::delete' => ['privates', '.service_locator.De_eRYO', 'get_ServiceLocator_DeERYOService', true],
            'App\\Controller\\AttachementController::edit' => ['privates', '.service_locator.De_eRYO', 'get_ServiceLocator_DeERYOService', true],
            'App\\Controller\\AttachementController::index' => ['privates', '.service_locator.Kwm52m8', 'get_ServiceLocator_Kwm52m8Service', true],
            'App\\Controller\\AttachementController::new' => ['privates', '.service_locator.Kwm52m8', 'get_ServiceLocator_Kwm52m8Service', true],
            'App\\Controller\\AttachementController::show' => ['privates', '.service_locator.Lp3XvEK', 'get_ServiceLocator_Lp3XvEKService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AttachementController:delete' => ['privates', '.service_locator.De_eRYO', 'get_ServiceLocator_DeERYOService', true],
            'App\\Controller\\AttachementController:edit' => ['privates', '.service_locator.De_eRYO', 'get_ServiceLocator_DeERYOService', true],
            'App\\Controller\\AttachementController:index' => ['privates', '.service_locator.Kwm52m8', 'get_ServiceLocator_Kwm52m8Service', true],
            'App\\Controller\\AttachementController:new' => ['privates', '.service_locator.Kwm52m8', 'get_ServiceLocator_Kwm52m8Service', true],
            'App\\Controller\\AttachementController:show' => ['privates', '.service_locator.Lp3XvEK', 'get_ServiceLocator_Lp3XvEKService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AttachementController::delete' => '?',
            'App\\Controller\\AttachementController::edit' => '?',
            'App\\Controller\\AttachementController::index' => '?',
            'App\\Controller\\AttachementController::new' => '?',
            'App\\Controller\\AttachementController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AttachementController:delete' => '?',
            'App\\Controller\\AttachementController:edit' => '?',
            'App\\Controller\\AttachementController:index' => '?',
            'App\\Controller\\AttachementController:new' => '?',
            'App\\Controller\\AttachementController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
