<?php

namespace ContainerU7taWFo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttachementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.De_eRYO.App\Entity\Attachement' shared service.
     *
     * @return \App\Entity\Attachement
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.De_eRYO": it references class "App\\Entity\\Attachement" but no such service exists.');
    }
}
