<?php

namespace ContainerU7taWFo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttachementTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AttachementType' shared autowired service.
     *
     * @return \App\Form\AttachementType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AttachementType.php';

        return $container->privates['App\\Form\\AttachementType'] = new \App\Form\AttachementType();
    }
}
