<?php

namespace ContainerGRl8uvv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kwm52m8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Kwm52m8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Kwm52m8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'attachementRepository' => ['privates', 'App\\Repository\\AttachementRepository', 'getAttachementRepositoryService', true],
        ], [
            'attachementRepository' => 'App\\Repository\\AttachementRepository',
        ]);
    }
}
