<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGRl8uvv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGRl8uvv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGRl8uvv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGRl8uvv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGRl8uvv\App_KernelDevDebugContainer([
    'container.build_hash' => 'GRl8uvv',
    'container.build_id' => '403027fa',
    'container.build_time' => 1649360413,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGRl8uvv');
